### ISSUE TITLE
Mekanism Enrich iron task not recognising completion

### ISSUE THREAD

**Issue by McKitten** [The-Nexus-Project/Limitless-3#144]
### Describe your issue, what happened?
I thought now that I had the enrichment chamber auto feeding the metallurgic infuser I'd give it a test run and complete one of the quest book tasks at the same time. It didn't trigger the first time (in 1.9.6) so I thought I would confirm (in 1.9.7) and am holding 4 enriched iron in my hand even opened the quest book from the inventory menu in top left.
Nada.
It is not recognizing it's completion.

# On a server
Yes but one I admin remotely (not paid).

**Comment by Gbergz** [comment]
Ah whoops that's a miss by me. I'll fix it in 1.9.8
You gotta make Enriched Carbon before making that item (easy enough in the meantime).

I accidentally added Enriched Carbon as a dependency. Which shouldn't be there obviously.
Thanks for the report.

Edit: Or rather I think I had a reasoning behind doing it like that bcs you "need"  enriched carbon to make enriched iron. But I now also realize that you can use any coal item. Enriched Carbon just gives you more use out of 1 coal.

Edit 2: Also I probably don't need to fix this, but I'll do it anyways. Since it makes more sense vs what it is now.

**Comment by McKitten** [comment]
Just had the same thing happen with the inferium gemstone and sword.

**Comment by Gbergz** [comment]
Are you by any chance crafting these in a Refined Storage Network / Ae2 network? You need to place the Quest items in your inventory for them to trigger properly. I recently played and completed the inferium sword & gemstone no problems.

**Comment by McKitten** [comment]
Yes I am but I had them in my hand when double checking the quest.
I got the reward for diamond pick a few moments later but without the gemstone recognising I was not prepared to continue further with its build also.

**Comment by Gbergz** [comment]
Well I can't reproduce the issue with Inferium etc not completing. Completes every time in my testings.

**Comment by McKitten** [comment]
It seems a parent quest - the prosperity gemstone, needed to be completed first.
It dominoed the others once i made another gemstone for a new infusion crystal.

**Comment by Gbergz** [comment]
Yes ofcourse. You need the prosperity gemstone to create any higher tiered gemstone.
