### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Skylife27** [The-Nexus-Project/Limitless-3#218]
I am not using Optifine
### Describe your issue, what happened?

The game keeps crashing either im lucky enough to get in and try to join a server but failing or not able to load the thing
### To Reproduce

1. Go to 'CurseForge'
2. Click on 'Play'
3. Scroll down to 'No scrolling'

### Expected behavior

Being able to join things
### Screenshots

It just stops working no error code or anything

### Crash Reports & Logs (Don't paste entire crash reports here.)
No crash reports at all
### Affected Version
1.16.5
- Pack Version: 
- On a server?:

**Comment by Gbergz** [comment]
Try another launcher than CurseForge, it tends to have issues.

- GD Launcher: https://gdevs.io/#downloadContainer
- MultiMC: https://multimc.org/#Download | Side note:
(Be sure to change to Development Channel in Settings if you're going to-
download through the MultiMC Launcher! Otherwise it will download an old pack version.)

**Comment by Skylife27** [comment]
So i switched over to GD Launcher and it seems to be working now thank you very much
