### ISSUE TITLE
[1.10.7] Squid spawns broken/don't exist?

### ISSUE THREAD

**Issue by TheMasterTM69** [The-Nexus-Project/Limitless-3#220]
I've started a new world and got a nice island spawn, but i got to the point where i have to go out and explore to get more stuff to progress, one of those things was black dye. Usually i'd get it by killing a few squids, but for some reason i cant find a single one, and i looked for over 30 minutes in oceans, rivers, and where ever else i thought a squid might spawn but i couldn't find any.
Is this a bug with the pack or do i maybe have to tweak some config files? (even AFK'd on peaceful near an ocean to maybe get one but nope)

**Comment by Gbergz** [comment]
Overall mob spawns in the modpack are 10 times slower compared to vanilla to reduce lag. So this might be the cause, because I've seen multiple squids in my test playthroughs. This is done in the performant mod.

You can however speed it up to vanilla speed again by going into the `performant-common.toml` config file and changing
`spawnInterval = 10` to 	`spawnInterval = 1` 1 = vanilla value.

**Comment by TheMasterTM69** [comment]
Ah! good to know! thanks, will change it to a smaller value.
