### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by jaideepheer** [The-Nexus-Project/Limitless-3#45]
### Describe your issue, what happened?
After playing for a while the game starts hitching frequently. I believe this is caused due to the garbage collector trying to clean up a memory leak.

### To Reproduce
1. Open a world.
2. Close the world to go back to the main menu.
3. Open the world again.
4. After a few tries, notice the game having lag hitches. If you open the debug text (F3), you will notice the memory used drops significantly after the lag spike ends.

### Expected behavior
No lag spikes. No memory leaks.

### Affected Version
- Pack Version:  1.8.0 (also seen in 1.7.5)
- On a server?: No, local single player. (World created on pack v1.7.5)

**Comment by choekstr** [comment]
This has been an issue since the 1.10 MC days and some heavy packs need a full restart to stop this happening.  I have 8GB allocated to the pack and last night mine was sitting at 10GB used with a 13GB commit footprint and it was pausing for 20 seconds, 1 second of play and doing it nonstop.  Had to stop playing for the night :(

I guess it's to be expected with such a large amount of mods, early days of 1.16 mods and early days of 1.16 forge versions.
